
services:

  geolocator-service:
    build:
      context: ./server/geolocator-service
    develop:
      watch:
        - action: rebuild
          path: ./server/geolocator-service
    ports:
      - "5000"
    stop_signal: SIGINT

  iss-distance-service:
    build:
      context: ./server/iss-distance-service
    develop:
      watch:
        - action: rebuild
          path: ./server/iss-distance-service
    ports:
      - "5000"
    stop_signal: SIGINT

  gateway:
    build:
      context: ./server/gateway
    develop:
      watch:
        - action: rebuild
          path: ./server/gateway
    ports:
      - "5000"
    environment:
      - GEOLOCATOR_SERVICE_URL=http://geolocator-service:5000
      - ISS_DISTANCE_SERVICE_URL=http://iss-distance-service:5000
    stop_signal: SIGINT

  frontend:
    build:
      context: ./frontend
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    ports:
      - "5000:5000"
    environment:
      - GATEWAY_URL=http://gateway:5000
    stop_signal: SIGINT
