services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./backend-configs/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # grpc
      - "4318:4318" # http
      - "8889:8889" # prometheus endpoint

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./backend-configs/tempo.yml:/etc/tempo.yaml
    ports:
      - "3200"    
      - "4317"    # otlp grpc
      - "4318"    # otlp http

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "4317" # grcp
      - "4318" # http

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./backend-configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["--config.file=/etc/loki/loki-config.yml"]
    volumes:
      - ./backend-configs/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./backend-configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"

volumes:
  grafana_data:
