receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"

exporters:
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"

  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp/loki, debug]
